name: Node.js CI

on:
  push:
    branches:
      - kevin-main  # name of the branch trigger will run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # as per requirement

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
